### ISSUE TITLE
Using Nix for these scripts

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/sysext#1]
Maybe it would be a cool idea to use Nix for all these scripts, considering it would make them completely reproducible independently of whatever distro someone uses, or what packages they have on their systems... They also could be bundled into a OCI image with all required dependencies to run them if that would be better!

**Comment by bketelsen** [comment]
Interesting idea. How much of Nix do you have to ship to take a single binary with you? like `neovim` for example?

**Comment by tulilirockz** [comment]
It shouldnt be too much of a hassle to package these scripts, we just need their dependencies and write some functions and thats it, we dont even need to change the scripts in any way. Im going to make a PR showcasing that later today

**Comment by bketelsen** [comment]
`nix bundle nixpkgs#duf` creates a file called `duf` which is a symlink to a file in the nix store. copy that file and rename it to `duf` and put it in your path on a machine without nix and it works perfectly.

Nix creates self-executing archive files. `arx` format, which is new to me. It contains the binary and all deps in one file. works the same as a regular executable, but the first invocation was a little slower than usual.

So you're onto something @tulilirockz - this could be awesome.

Next step would be to build a wrapper around the whole process that takes a nix reference and outputs a sysext. `build-from-nix nixpkgs#duf`

I'm curious if there are any hidden gotchas or negatives to this, other than the binaries being kind of on the fatter side since they're static+deps all bundled together.

**Comment by bketelsen** [comment]
inside a `nixos/nix` container you run this:
`nix bundle nixpkgs#hello --extra-experimental-features nix-command --extra-experimental-features flakes
`

**Comment by tulilirockz** [comment]
Pretty sure there shouldnt be any gotchas from that, considering that these bundled nix packages, when done without a sandbox, are pretty much just statically compiled programs. It would be pretty awesome to just have a flake that has all the scripts in it, then use Github Action with nix to bundle them, and release with "gh release"

**Comment by tulilirockz** [comment]
Also, an update on this nix packaging situation. Im currently writing a PR for Blincus that does just that, it would be so awesome to just distribute these scripts without needing a compiled language or anything like that!

**Comment by tulilirockz** [comment]
The only thing I got a bit caught up on was that the function that I'm using to package these scripts `symlinkJoin`, adds them to their relative PATHs, that might generate some kind of conflict depending on what is the name of the script. E.g.: When packaging `Blincus` as a nix package, I ran into a infinite recursion because the script `install` called itself indefinitely, instead of running GNU Install.

**Comment by tulilirockz** [comment]
Although there are some drawbacks listed on https://github.com/matthewbauer/nix-bundle, namely the slow startup at first run. Also the fact that you need to specify every single dependency the script has, like stuff like "gnugrep", or "gnutar" and whatever else, that might be somewhat of a maintenance burden

**Comment by tulilirockz** [comment]
This could be even cooler considering NixOS has some other [bundlers](https://github.com/NixOS/bundlers/blob/master/flake.nix) like "toRPM"... that generates RPM packages! It would be amazing to just distribute that to everyone, like, as easily as that!

**Comment by bketelsen** [comment]
see commit https://github.com/ublue-os/sysext/commit/3638ec2c7eb98d812e6089f847d861596de09fc3

the `just albafetch` recipe builds a nix generic container, then calls `nix_bundle_sysext.sh` which takes a flakeref (can be nixpkgs#hello format or a URL format), runs the nix bundle, creates the extension.

**Comment by bketelsen** [comment]
```~ took 11m53s 
❯ albafetch
          /:-------------:\            bjk@beast
       :-------------------::          ---------
     :-----------/shhOHbmp---:\        Uptime: 13h 54m
   /-----------omMMMNNNMMD]  ---:      ---------------
  :-----------sMMMMNMNMP.    ---:      OS: Fedora Linux 39.20240115.0 (Bluefin) x86_64
 :-----------:MMMdP-------    ---\     Kernel: 6.6.9-200.fc39.x86_64
,------------:MMMd--------    ---:     Desktop: GNOME
:------------:MMMd-------    .---:     Shell: nix-user-chroot
:----    oNMMMMMMMMMNho     .----:     Terminal: xterm-256color
:--     .+shhhMMMmhhy++   .------/     ------------------------
:-    -------:MMMd--------------:      Host: XPS 8950 
:-   --------/MMMd-------------;       CPU: Intel Core i7-12700 @ 0.8 GHz (20) 
:-    ------/hMMMy------------:        GPU: TU104 [GeForce RTX 2080
:-- :dMNdhhdNMMNo------------;         Memory: 11292 MiB / 64016 MiB (17%)
:---:sdNMMMMNds:------------:          
:------:://:-------------::                                    
:---------------------://     
```

**Comment by tulilirockz** [comment]
Moved to #3
