### ISSUE TITLE
Proposal: Changing the way these overlays work to integrate nix into them

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/sysext#3]
Sorry for always talking about nix, but it really could be quite useful for this project. Like, I am working on an architecture for this project on my personal fork that uses the nix store for these system extensions.

Basically, the idea is to use nix packages instead of manually fetching static binaries for every program these extensions aim to use, but you can't just copy stuff from the /nix/store off to anywhere you want, so the idea was to:

- Make a symlink farm FHS-compatible root with all the `/nix/store` symlinks for the extension
- Make readonly bind-mount or overlayfs onto `/nix` with the contents of an entire nix store so that all the `.so`s work on the symlinks
- Do that for all extensions

That would be just like the nix bundles, but unbundled, without nix itself being necessarily installed on the host system, removing all the slow unpacking time for every package!

The final layout would look pretty much like this:

1. User declares the configuration on a `config.json` file (stuff like sysext-name, OS, arch, and packages)
2. Dockerfile with nix generates tar file with `/nix/store` with all the depencies for the target package
3. Dockerfile also makes a symlink tree with symlinks to that `/nix/store` (`/usr/bin/hello -> /nix/store/HASH-name-VERSION/bin/hello`)
4. Utility script or program unpacks tar file with the nix store, dumps it into `/var/cache/sysext-layers/${layer-name}`
5. Utility generates a `systemd-sysext` compatible squashfs file from the symlink tree
6. Utility overlays (or bind-mounts) `/var/cache/sysext-layers/${layer-name}/nix` on top of `/nix`
7. Utility activates `systemd-sysext` and `systemd-confext` and overlays your target nix-based extension
8. User is happy!

Overlaying stuff on `/nix/store` should work since all of the packages/libraries inside of it are completely self-contained and thus, completely bind-mount compatible, just like [Docker](https://youtu.be/l17oRkhgqHE?feature=shared&t=1603) does with their nix-based docker images (but instead of being a docker image its your entire system).

This is my [personal fork](https://github.com/tulilirockz/sysext/tree/feat-nix-based-sysextensions), you can check out progress for this proposal in it!

**Comment by bketelsen** [comment]
no apologies necessary this sounds fascinating and works around many problems I've already had with other approaches. Please keep this issue updated with your progress

**Comment by tulilirockz** [comment]
Same thing in the PR!
